#!/usr/bin/env python
import os
import sys
import fnmatch

def recursive_glob(rootdir='.', pattern='*'):
	"""Recursively glob files from a root directory."""
	matches = []
	for root, dirnames, filenames in os.walk(rootdir):
		for filename in fnmatch.filter(filenames, pattern):
			matches.append(os.path.join(root, filename))
	return matches

env = SConscript("../godot-cpp-4.2/SConstruct")

env.Append(CPPPATH=["/"])
cpp_sources = recursive_glob('.', '*.cpp')

# Keep the file name in lowercase to prevent case-sensitive file system bugs
export_path = "../project/bin/imgtran{}{}"
library = env.SharedLibrary(
	export_path.format(env["suffix"], env["SHLIBSUFFIX"]),
	source=cpp_sources,
)

Default(library)
